CREATE TABLE IF NOT EXISTS laps (
    Time VARCHAR,
    Driver VARCHAR,
    DriverNumber VARCHAR,
    LapTime VARCHAR,
    LapNumber DOUBLE,
    Stint DOUBLE,
    PitOutTime VARCHAR,
    PitInTime VARCHAR,
    Sector1Time VARCHAR,
    Sector2Time VARCHAR,
    Sector3Time VARCHAR,
    SpeedI1 DOUBLE,
    SpeedI2 DOUBLE,
    SpeedFL DOUBLE,
    SpeedST DOUBLE,
    Compound VARCHAR,
    TyreLife DOUBLE,
    FreshTyre BOOLEAN,
    Team VARCHAR,
    LapStartTime VARCHAR,
    TrackStatus VARCHAR,
    Position DOUBLE,
    IsPersonalBest BOOLEAN
);
